### ISSUE TITLE
`lint_package()` and `fix_package()` internals are broken

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/flint#53]
```
lint(
    path,
    [...]
```

should be

```
lint(
    paths,
    [...]
```

Requires #52 to be fixed first.

**Comment by etiennebacher** [comment]
closed by [29aa3ab](https://github.com/etiennebacher/flint/commit/29aa3ab0eb003b1f3c120f75e3f1129a9e231daf)

**Comment by jrosell** [comment]
Thanks. I will try how it works.
